### ISSUE TITLE
Add support for non-OIDC audience

### ISSUE THREAD

**Issue by twistedstream** [openidconnect/openidconnect-playground#11]
Currently the debugger view only enables you to perform an `/authorize` call that results in an `access_token` for the OIDC provider itself. We should add support for obtaining a token for a different resource server (audience). This would require:
1. Addition of the optional `audience` parameter
2. Allowing custom scopes besides the standard OIDC scopes (eg. `read:calendar`).

The initial **Request** would look something like this:
![image](https://cloud.githubusercontent.com/assets/3535918/19215996/e7949aba-8d72-11e6-83eb-f645e145509e.png)

**Comment by jaredhanson** [comment]
This is not part of OpenID Connect itself, but rather is a feature of authentication servers that are *also* authorization servers for arbitrary APIs.  Auth0 does support this feature, however we run the risk of creating a steeper learning curve by adding this to the OIDC playground.  Since the playground is OpenID Connect specific, I'd recommend we limit the features we educate people about to only those that are offered by OpenID Connect itself.

**Comment by twistedstream** [comment]
@jaredhanson: I created PR #12 that enables audience per this issue. However, it only enables it for the **Auth0** server template and not for **Google** or **Custom**. While I agree with you on your point, having this one feature would be extremely valuable for demos of how Auth0 specifically can be both an OIDC provider _and_ an authorization server.  Perhaps we can add a link for that field in the debugger to our docs page so it's more clear to end users:
![image](https://cloud.githubusercontent.com/assets/3535918/19272803/98cf2386-8f8f-11e6-852a-50f60fdd24d2.png)

**Comment by twistedstream** [comment]
Closing for same reason that the PR (#12) was closed
